version: '3.3'

services:
  doccano:
    container_name: doccano_srpski_rizik
    image: doccano/doccano
    restart: always
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: Admin123!
      ADMIN_EMAIL: safyrix@protonmail.ch
    ports:
      - "8000:8000"
    volumes:
      - doccano_data:/doccano/data

volumes:
  doccano_data:
